### ISSUE TITLE
onSlide not called when peekHeight changed in COLLAPSED state

### ISSUE THREAD

**Issue by davidbilik** [trafi/anchor-bottom-sheet-behavior#16]
Hello, I am switching content in BottomSheet with attached AnchorBottomSheetBehavior and each content has different peek height. It works fine if I call something like
```
bottomSheetBehavior.peekHeight = activeFragment.peekHeight
bottomSheetBehavior.state = AnchorBottomSheetBehavior.STATE_COLLAPSED
```
and the behavior is not in COLLAPSED state. However if it is COLLAPSED, the peek height changes abruptly without animation and without onSlide callback so I cannot react to this change. Is there any way how to perform animation of the peekHeight (without manual animating this property) and to make callback to fire?
Thanks

**Comment by justasm** [comment]
Not with the current behavior. You could try temporarily switching to a different state, e.g.
```kotlin
state = STATE_EXPANDED
peekHeight = newPeekHeight
state = STATE_COLLAPSED
```
although I haven't tested if this would work.

**Comment by davidbilik** [comment]
It works 💪 thanks :)
