### ISSUE TITLE
Not Sync

### ISSUE THREAD

**Issue by mnssurendran** [trafi/anchor-bottom-sheet-behavior#4]
Not Syncing   implementation 'com.trafi:anchor-bottom-sheet-behavior:0.9-alpha'

**Comment by justasm** [comment]
Sorry, this is due to a an issue in https://jitpack.io, which is used to host the published library.

Please check there for solutions and / or workarounds for the time being: https://github.com/jitpack/jitpack.io/issues/2189

**Comment by mnssurendran** [comment]
I don't know how to configure the workaround specified there. Can you provide jar file in the release tag? (https://github.com/trafi/anchor-bottom-sheet-behavior/releases)

**Comment by justasm** [comment]
Sure, [done](https://github.com/trafi/anchor-bottom-sheet-behavior/releases/tag/0.9.1-alpha).

**Comment by justasm** [comment]
For reference you can get the files from
`https://jitpack.io/com/trafi/anchor-bottom-sheet-behavior/0.9.1-alpha/anchor-bottom-sheet-behavior-{VERSION}.aar`, e.g. [0.9.1-alpha](https://jitpack.io/com/trafi/anchor-bottom-sheet-behavior/0.9.1-alpha/anchor-bottom-sheet-behavior-0.9.1-alpha.aar).

**Comment by justasm** [comment]
@mnssurendran the issue seems to have been resolved and syncing should work again -- could you please confirm?

**Comment by mnssurendran** [comment]
Thanks @justasm. It's working
