### ISSUE TITLE
scrollView inside bottomSheet

### ISSUE THREAD

**Issue by UnicornDigital** [trafi/anchor-bottom-sheet-behavior#5]
scroll view and list view have scroll problem when we put them inside anchor-bottom-sheet-behavior

actually android:nestedScrollingEnabled="true" not woking while its working with normal bottom sheet.

**Comment by justasm** [comment]
Hi, could you please provide:
- a demonstration of expected behavior
- a demonstration of actual behavior
- ideally, a code sample showing usage

We haven't tested `ScrollView` and `ListView` children, although we use `RecyclerView`s extensively.

**Comment by UnicornDigital** [comment]
ScrollView and ListView scroll down normally but can not scrolled up.

but NestedScrollView working right Instead ScrollView

and NonScrollListView inside NestedScrollView working right instead ListView.

thanks.
